COMMAND_METADATA = {
    "init": {"nature": "writes framework artifacts and approved projections", "permissions": "project directory", "preconditions": "valid path"},
    "scan": {"nature": "read-only detection", "permissions": "project read", "preconditions": "path exists"},
    "doctor": {"nature": "read-only diagnostics", "permissions": "project read", "preconditions": "none"},
    "test": {"nature": "runs configured commands", "permissions": "subprocesses in project", "preconditions": "configured runners"},
    "check": {"nature": "read-only quality gate", "permissions": "project read", "preconditions": "none"},
    "security scan": {"nature": "read-only safety gate", "permissions": "project/Git read", "preconditions": "Git for complete scope"},
    "integration": {"nature": "lists, installs and validates local agent projections", "permissions": "declared agent paths", "preconditions": "project root"},
    "learn": {"nature": "writes optional redacted session memory", "permissions": "project .framework directory", "preconditions": "valid project or disabled mode"},
    "quiz": {"nature": "generates or runs optional knowledge assessment", "permissions": "project .framework directory and explicitly authorized provider", "preconditions": "valid project or disabled mode"},
    "test create": {"nature": "agentic feature test specification and generation", "permissions": "authorized local agent may write test files and .framework/quality/features", "preconditions": "complete description and conflict-free instruction chain"},
    "test explain": {"nature": "AST/import analysis and generated comments", "permissions": "writes only managed explanation blocks", "preconditions": "supported test language"},
    "test approve": {"nature": "records a test content hash", "permissions": "writes approval metadata", "preconditions": "test exists"},
    "tradeoff": {"nature": "agentic advisory request", "permissions": "read-only source context unless an authorized command is configured", "preconditions": "instruction chain has no conflict"},
    "implement": {"nature": "agentic implementation request", "permissions": "authorized local command may modify project", "preconditions": "failing test and valid instruction chain"},
    "fix": {"nature": "agentic bug-fix request", "permissions": "authorized local command may modify project", "preconditions": "valid instruction chain"},
    "review": {"nature": "read-only Git diff review", "permissions": "project/Git read", "preconditions": "none"},
    "sync": {"nature": "deterministic generated-block synchronization", "permissions": "writes managed explanation blocks", "preconditions": "supported test files"},
    "inspect": {"nature": "read-only symbol inspection", "permissions": "project read", "preconditions": "none"},
    "update": {"nature": "deterministic framework artifact update", "permissions": "writes managed explanation blocks", "preconditions": "valid project"},
    "scripts generate": {"nature": "local-agent-generated stack scripts", "permissions": "authorized local agent may write .framework/scripts", "preconditions": "valid instruction chain"},
}
