SCHEMA_VERSION = 1
SCHEMA = """
CREATE TABLE IF NOT EXISTS metadata (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS projects (id TEXT PRIMARY KEY, root_path TEXT NOT NULL, profile TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS applications (id TEXT PRIMARY KEY, project_id TEXT NOT NULL, path TEXT NOT NULL, data TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS adapters (id TEXT PRIMARY KEY, version TEXT NOT NULL, capabilities TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS findings (id TEXT PRIMARY KEY, category TEXT NOT NULL, path TEXT, line INTEGER, data TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS generated_artifacts (path TEXT PRIMARY KEY, source TEXT NOT NULL, version TEXT NOT NULL, checksum TEXT NOT NULL, state TEXT NOT NULL);
"""
